# Generated by Django 4.0.4 on 2022-04-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_taxrates_user_state_taxcalc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='user_type',
        ),
    ]
