# Generated by Django 4.0.4 on 2022-04-13 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalc',
            name='due_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxcalc',
            name='finalAmt',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='taxcalc',
            name='paid_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
