# Generated by Django 4.0.4 on 2022-04-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0009_alter_taxcalc_due_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalc',
            name='pan',
            field=models.CharField(default='test', max_length=15),
            preserve_default=False,
        ),
    ]
