# Generated by Django 4.0.4 on 2022-04-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0012_remove_user_state_user_states'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='states',
            new_name='state',
        ),
    ]
